import { Question } from '../types';

export const vocabulary: Question[] = [
  { fi: "Hei", en: "Hello", kappale: 1 },
  { fi: "ja", en: "and", kappale: 1 },
  { fi: "Tervetuloa!", en: "Welcome!", kappale: 1 },
  { fi: "Moi!", en: "Hi!", kappale: 1 },
  { fi: "Anteeksi!", en: "Excuse me!", kappale: 1 },
  { fi: "onko", en: "is", kappale: 1 },
  { fi: "täällä", en: "here", kappale: 1 },
  { fi: "suomen kurssi", en: "course in Finnish", kappale: 1 },
  { fi: "joo", en: "yes", kappale: 1 },
  { fi: "Kuka sinä olet?", en: "Who are you?", kappale: 1 },
  { fi: "minä", en: "I", kappale: 1 },
  { fi: "olla", en: "be", kappale: 1 },
  { fi: "entä", en: "what about", kappale: 1 },
  { fi: "sinä", en: "you", kappale: 1 },
  { fi: "Hauska tutustua!", en: "Nice to meet you!", kappale: 1 },
  { fi: "Kiitos samoin!", en: "Likewise!", kappale: 1 },
  { fi: "Mitä sinulle kuuluu?", en: "How are you?", kappale: 1 },
  { fi: "Minulle kuuluu hyvää.", en: "I'm fine, thank you.", kappale: 1 },
  { fi: "Entä sinulle?", en: "And you?", kappale: 1 },
  { fi: "Ihan hyvää", en: "kiitos.,I'm fine, thank you.", kappale: 1 },
  { fi: "hän", en: "he, she", kappale: 1 },
  { fi: "Kuinka vanha sinä olet?", en: "How old are you?", kappale: 1 },
  { fi: "opettaja", en: "teacher", kappale: 1 },
  { fi: "tulla", en: "(to) come", kappale: 1 },
  { fi: "Huomenta!", en: "Good morning!", kappale: 1 },
  { fi: "Mikä sinun nimi on?", en: "What's your name?", kappale: 1 },
  { fi: "Minun nimeni on...", en: "My name is...", kappale: 1 },
  { fi: "Miten se kirjoitetaan?", en: "How do you spell it?", kappale: 1 },
  { fi: "etunimi", en: "first name", kappale: 1 },
  { fi: "sukunimi", en: "last name", kappale: 1 },
  { fi: "Huomenta!", en: "Morning!", kappale: 1 },
  { fi: "Hyvää huomenta!", en: "Good morning!", kappale: 1 },
  { fi: "Päivää!", en: "Afternoon!", kappale: 1 },
  { fi: "Hyvää päivää!", en: "Good afternoon!", kappale: 1 },
  { fi: "Iltäa!", en: "Evening!", kappale: 1 },
  { fi: "Hyvää iltaa!", en: "Good evening!", kappale: 1 },
  { fi: "Hei hei!", en: "Bye bye!", kappale: 1 },
  { fi: "Nähdään huomenna!", en: "See you tomorrow!", kappale: 1 },
  { fi: "Moi moi!", en: "Bye!", kappale: 1 },
  { fi: "Moikka!", en: "Bye!", kappale: 1 },
  { fi: "Heippa!", en: "Bye!", kappale: 1 },
  { fi: "Näkemiin!", en: "Goodbye!", kappale: 1 },
  { fi: "Joo.", en: "Yeah.", kappale: 1 },
  { fi: "Ei.", en: "No.", kappale: 1 },
  { fi: "Kyllä.", en: "Yes.", kappale: 1 },
  { fi: "Ole hyvä!", en: "Thank you!", kappale: 1 },
  { fi: "Kiitos!", en: "Thank you!", kappale: 1 },
  { fi: "Ei kestä!", en: "You're welcome!", kappale: 1 },
  { fi: "Anteeksi!", en: "Sorry!", kappale: 1 },
  { fi: "Ei se mitään!", en: "It's all right!", kappale: 1 },
  { fi: "Tervetuloa!", en: "Welcome!", kappale: 1 },
  { fi: "viikonpäivät", en: "days of the week", kappale: 1 },
  { fi: "Mikä päivä tänään on?", en: "What day is it today?", kappale: 1 },
  { fi: "millon", en: "when", kappale: 1 },
  { fi: "Hauskaa viikonloppua!", en: "Have a nice weekend!", kappale: 1 },
  { fi: "maanantai", en: "Monday", kappale: 1 },
  { fi: "tiistai", en: "Tuesday", kappale: 1 },
  { fi: "keskiviikko", en: "Wednesday", kappale: 1 },
  { fi: "torstai", en: "Thursday", kappale: 1 },
  { fi: "perjantai", en: "Friday", kappale: 1 },
  { fi: "lauantai", en: "Saturday", kappale: 1 },
  { fi: "sunnuntai", en: "Sunday", kappale: 1 },
  { fi: "viikonloppu", en: "weekend", kappale: 1 },
  { fi: "toissapäivänä", en: "day before yesterday", kappale: 1 },
  { fi: "eilen", en: "yesterday", kappale: 1 },
  { fi: "tänään", en: "today", kappale: 1 },
  { fi: "huomenna", en: "tomorrow", kappale: 1 },
  { fi: "ylihuomenna", en: "day after tomorrow", kappale: 1 },
  { fi: "nolla", en: "zero", kappale: 1 },
  { fi: "yksi", en: "one", kappale: 1 },
  { fi: "kaksi", en: "two", kappale: 1 },
  { fi: "kolme", en: "three", kappale: 1 },
  { fi: "neljä", en: "four", kappale: 1 },
  { fi: "viisi", en: "five", kappale: 1 },
  { fi: "kuusi", en: "six", kappale: 1 },
  { fi: "seitsemän", en: "seven", kappale: 1 },
  { fi: "kahdeksan", en: "eight", kappale: 1 },
  { fi: "yhdeksän", en: "nine", kappale: 1 },
  { fi: "kymmenen", en: "ten", kappale: 1 },
  { fi: "yksitoista", en: "eleven", kappale: 1 },
  { fi: "kaksitoista", en: "twelve", kappale: 1 },
  { fi: "kolmetoista", en: "thirteen", kappale: 1 },
  { fi: "neljätoista", en: "fourteen", kappale: 1 },
  { fi: "viisitoista", en: "fifteen", kappale: 1 },
  { fi: "kuusitoista", en: "sixteen", kappale: 1 },
  { fi: "seitsemäntoista", en: "seventeen", kappale: 1 },
  { fi: "kahdeksantoista", en: "eighteen", kappale: 1 },
  { fi: "yhdeksäntoista", en: "nineteen", kappale: 1 },
  { fi: "kaksikymmentä", en: "twenty", kappale: 1 },
  { fi: "kaksikymmentäyksi", en: "twenty-one", kappale: 1 },
  { fi: "kaksikymmentäkaksi", en: "twenty-two", kappale: 1 },
  { fi: "kolmekymmentä", en: "thirty", kappale: 1 },
  { fi: "neljäkymmentä", en: "forty", kappale: 1 },
  { fi: "viisikymmentä", en: "fifty", kappale: 1 },
  { fi: "kuusikymmentä", en: "sixty", kappale: 1 },
  { fi: "seitsemänkymmentä", en: "seventy", kappale: 1 },
  { fi: "kahdeksankymmentä", en: "eighty", kappale: 1 },
  { fi: "yhdeksänkymmentä", en: "ninety", kappale: 1 },
  { fi: "sata", en: "one hundred", kappale: 1 },
  { fi: "satakaksi", en: "one hundred and one", kappale: 1 },
  { fi: "kaksisataa", en: "two hundred", kappale: 1 },
  { fi: "kolmesataa", en: "three hundred", kappale: 1 },
  { fi: "tuhat", en: "thousand", kappale: 1 },
  { fi: "kaksituhat", en: "two thousand", kappale: 1 },
  { fi: "viisisataatuhatta", en: "five hundred thousand", kappale: 1 },
  { fi: "miljoona", en: "million", kappale: 1 },
  { fi: "kaksi miljoonaa", en: "two million", kappale: 1 },
  { fi: "portugali", en: "Portuguese", kappale: 2 },
  { fi: "ai niin", en: "right", kappale: 2 },
  { fi: "tietysti", en: "of course", kappale: 2 },
  { fi: "ajaa", en: "(to) drive", kappale: 2 },
  { fi: "auto", en: "car", kappale: 2 },
  { fi: "bussipysäkki", en: "bus stop", kappale: 2 },
  { fi: "missä", en: "where", kappale: 2 },
  { fi: "asua", en: "(to) live", kappale: 2 },
  { fi: "numero", en: "number", kappale: 2 },
  { fi: "vaan", en: "but", kappale: 2 },
  { fi: "nyt", en: "now", kappale: 2 },
  { fi: "maksaa", en: "(to) cost; (to) pay", kappale: 2 },
  { fi: "pallo", en: "ball", kappale: 2 },
  { fi: "ahaa", en: "oh, I see", kappale: 2 },
  { fi: "haluaisin", en: "I would like", kappale: 2 },
  { fi: "suklaa", en: "chocolate", kappale: 2 },
  { fi: "okei", en: "okay", kappale: 2 },
  { fi: "sinulle", en: "for you", kappale: 2 },
  { fi: "myös", en: "also", kappale: 2 },
  { fi: "vanilja", en: "vanilla", kappale: 2 },
  { fi: "mansikka", en: "strawberry", kappale: 2 },
  { fi: "selvä", en: "right", kappale: 2 },
  { fi: "tuleeko muuta", en: "anything else", kappale: 2 },
  { fi: "tässä", en: "here", kappale: 2 },
  { fi: "euro", en: "euro", kappale: 2 },
  { fi: "maa", en: "country; land", kappale: 2 },
  { fi: "kansalaisuus", en: "nationality", kappale: 2 },
  { fi: "kieli", en: "language; tongue", kappale: 2 },
  { fi: "Suomi", en: "Finland", kappale: 2 },
  { fi: "Ranska", en: "France", kappale: 2 },
  { fi: "Kreikka", en: "Greece", kappale: 2 },
  { fi: "Islanti", en: "Iceland", kappale: 2 },
  { fi: "Egypti", en: "Egypt", kappale: 2 },
  { fi: "Venäjä", en: "Russia", kappale: 2 },
  { fi: "Pakistan", en: "Pakistan", kappale: 2 },
  { fi: "suomalainen", en: "Finnish", kappale: 2 },
  { fi: "ranskalainen", en: "French", kappale: 2 },
  { fi: "kreikkalainen", en: "Greek", kappale: 2 },
  { fi: "islantilainen", en: "Icelandic", kappale: 2 },
  { fi: "egyptiläinen", en: "Egyptian", kappale: 2 },
  { fi: "venäläinen", en: "Russian", kappale: 2 },
  { fi: "pakistanilainen", en: "Pakistani", kappale: 2 },
  { fi: "suomi", en: "Finnish", kappale: 2 },
  { fi: "ranska", en: "French", kappale: 2 },
  { fi: "kreikka", en: "Greek", kappale: 2 },
  { fi: "islanti", en: "Icelandic", kappale: 2 },
  { fi: "arabia", en: "Arabic", kappale: 2 },
  { fi: "venäjä", en: "Russia", kappale: 2 },
  { fi: "urdu", en: "Urdu", kappale: 2 },
  { fi: "Mistä sinä olet kotoisin?", en: "Where are you from?", kappale: 2 },
  { fi: "Minkämaalainen sinä olet?", en: "Which country are you from?", kappale: 2 },
  { fi: "Mitä kieltä sinä puhut?", en: "What language do you speak?", kappale: 2 },
  { fi: "olla kotoisin", en: "come from", kappale: 2 },
  { fi: "puhua", en: "(to) speak", kappale: 2 },
  { fi: "maailma", en: "world", kappale: 2 },
  { fi: "pohjoinen", en: "North", kappale: 2 },
  { fi: "Pohjois-Amerikka", en: "North America", kappale: 2 },
  { fi: "Etelä-Amerikka", en: "South America", kappale: 2 },
  { fi: "Eurooppa", en: "Europe", kappale: 2 },
  { fi: "Afrikka", en: "Africa", kappale: 2 },
  { fi: "Aasia", en: "Asia", kappale: 2 },
  { fi: "Australia", en: "Australia", kappale: 2 },
  { fi: "Etelämanner", en: "Antarctica", kappale: 2 },
  { fi: "ilmansuunnat", en: "points of the compass", kappale: 2 },
  { fi: "pohjoinen", en: "north", kappale: 2 },
  { fi: "etelä", en: "south", kappale: 2 },
  { fi: "itä", en: "east", kappale: 2 },
  { fi: "länsi", en: "west", kappale: 2 },
  { fi: "hinta", en: "price", kappale: 2 },
  { fi: "raha", en: "money", kappale: 2 },
  { fi: "Mitä tämä maksaa?", en: "How much does this cost?", kappale: 2 },
  { fi: "euro", en: "euro", kappale: 2 },
  { fi: "sentti", en: "cent", kappale: 2 },
  { fi: "seteli", en: "note, bill", kappale: 2 },
  { fi: "kolikko", en: "coin", kappale: 2 },
  { fi: "halpa", en: "cheap", kappale: 2 },
  { fi: "kallis", en: "expensive", kappale: 2 },
  { fi: "sähköposti", en: "e-mail", kappale: 3 },
  { fi: "mies", en: "man", kappale: 3 },
  { fi: "hyvä", en: "good", kappale: 3 },
  { fi: "ystävä", en: "friend", kappale: 3 },
  { fi: "kirjoittaa", en: "(to) write", kappale: 3 },
  { fi: "lähettäjä", en: "sender", kappale: 3 },
  { fi: "vastaanottaja", en: "recipient", kappale: 3 },
  { fi: "otsikko", en: "subject", kappale: 3 },
  { fi: "terveisiiä", en: "greetings", kappale: 3 },
  { fi: "englanniksi", en: "in English", kappale: 3 },
  { fi: "vaan", en: "but", kappale: 3 },
  { fi: "suomeksi", en: "in Finnish", kappale: 3 },
  { fi: "toivottavasti", en: "hopefully", kappale: 3 },
  { fi: "ymmärtää", en: "(to) understand", kappale: 3 },
  { fi: "hauska", en: "funny", kappale: 3 },
  { fi: "maanantaisin", en: "on Mondays", kappale: 3 },
  { fi: "keskiviikkoisin", en: "on Wednesdays", kappale: 3 },
  { fi: "torstaisin", en: "On Thursdays", kappale: 3 },
  { fi: "meidän", en: "our", kappale: 3 },
  { fi: "kiva", en: "nice", kappale: 3 },
  { fi: "minun", en: "my", kappale: 3 },
  { fi: "ystävä", en: "friend", kappale: 3 },
  { fi: "yleensä", en: "usually", kappale: 3 },
  { fi: "koti", en: "home", kappale: 3 },
  { fi: "lukea", en: "(to) read", kappale: 3 },
  { fi: "uutiset", en: "news", kappale: 3 },
  { fi: "etsiä töitä", en: "(to) look for a job", kappale: 3 },
  { fi: "joskus", en: "sometimes", kappale: 3 },
  { fi: "soittaa", en: "(to) play", kappale: 3 },
  { fi: "kitara", en: "guitar", kappale: 3 },
  { fi: "ilta", en: "evening", kappale: 3 },
  { fi: "olla töissä", en: "(to) work", kappale: 3 },
  { fi: "opiskelija-asunto", en: "student apartment", kappale: 3 },
  { fi: "pieni", en: "small", kappale: 3 },
  { fi: "siksi", en: "that's why", kappale: 3 },
  { fi: "muuttaa", en: "(to) move", kappale: 3 },
  { fi: "elokuu", en: "August", kappale: 3 },
  { fi: "uusi", en: "news", kappale: 3 },
  { fi: "täällä", en: "here", kappale: 3 },
  { fi: "kaunis", en: "beautiful", kappale: 3 },
  { fi: "ilma", en: "weather; air", kappale: 3 },
  { fi: "lämmin", en: "warm", kappale: 3 },
  { fi: "aste", en: "degree", kappale: 3 },
  { fi: "aurinko", en: "sun", kappale: 3 },
  { fi: "paistaa", en: "(to) shine", kappale: 3 },
  { fi: "yö", en: "night", kappale: 3 },
  { fi: "joskus", en: "sometimes", kappale: 3 },
  { fi: "vaikea", en: "hard", kappale: 3 },
  { fi: "nukkua", en: "(to) sleep", kappale: 3 },
  { fi: "koska", en: "because", kappale: 3 },
  { fi: "valoisa", en: "light", kappale: 3 },
  { fi: "millainen", en: "what kind", kappale: 3 },
  { fi: "sää", en: "weather", kappale: 3 },
  { fi: "paljon", en: "a lot", kappale: 3 },
  { fi: "terveisin", en: "greetings", kappale: 3 },
  { fi: "missä", en: "where", kappale: 3 },
  { fi: "täällä", en: "here", kappale: 3 },
  { fi: "tuolla", en: "over there", kappale: 3 },
  { fi: "siellä", en: "there", kappale: 3 },
  { fi: "nyt", en: "now", kappale: 3 },
  { fi: "vaan", en: "but", kappale: 3 },
  { fi: "toivottavasti", en: "hopefully", kappale: 3 },
  { fi: "että", en: "that", kappale: 3 },
  { fi: "myös", en: "also", kappale: 3 },
  { fi: "yleensä", en: "usually", kappale: 3 },
  { fi: "joskus", en: "sometimes", kappale: 3 },
  { fi: "siksi", en: "that's why", kappale: 3 },
  { fi: "koska", en: "because", kappale: 3 },
  { fi: "millainen", en: "what kind", kappale: 3 },
  { fi: "hyvä", en: "good", kappale: 3 },
  { fi: "huono", en: "bad", kappale: 3 },
  { fi: "kuuma", en: "hot", kappale: 3 },
  { fi: "kylmä", en: "cold", kappale: 3 },
  { fi: "vaikea", en: "hard", kappale: 3 },
  { fi: "helppo", en: "easy", kappale: 3 },
  { fi: "pieni", en: "small", kappale: 3 },
  { fi: "iso", en: "big", kappale: 3 },
  { fi: "suuri", en: "big", kappale: 3 },
  { fi: "uusi", en: "new", kappale: 3 },
  { fi: "vanha", en: "old", kappale: 3 },
  { fi: "kaunis", en: "beautiful", kappale: 3 },
  { fi: "ruma", en: "ugly", kappale: 3 },
  { fi: "lämmin", en: "warm", kappale: 3 },
  { fi: "viileä", en: "cool", kappale: 3 },
  { fi: "valoisa", en: "light", kappale: 3 },
  { fi: "pimeä", en: "dark", kappale: 3 },
  { fi: "paljon", en: "a lot", kappale: 3 },
  { fi: "vähän", en: "a little", kappale: 3 },
  { fi: "sää", en: "weather", kappale: 3 },
  { fi: "Millainen sää / ilma tänään on?", en: "What's the weather like today?", kappale: 3 },
  { fi: "On kaunis / hyvä ilma.", en: "It's beautiful weather.", kappale: 3 },
  { fi: "On huono ilma.", en: "It's terrible weather.", kappale: 3 },
  { fi: "aste", en: "degree", kappale: 3 },
  { fi: "kuuma", en: "hot", kappale: 3 },
  { fi: "helle", en: "heat", kappale: 3 },
  { fi: "lämmin", en: "warm", kappale: 3 },
  { fi: "viileä", en: "cool", kappale: 3 },
  { fi: "kylmä", en: "cold", kappale: 3 },
  { fi: "pakkanen", en: "frost", kappale: 3 },
  { fi: "aurinko", en: "sun", kappale: 3 },
  { fi: "paistaa", en: "(to) shine", kappale: 3 },
  { fi: "aurinkoinen", en: "sunny", kappale: 3 },
  { fi: "pilvinen", en: "cloudy", kappale: 3 },
  { fi: "puolipilvinen", en: "partly cloudy", kappale: 3 },
  { fi: "selkeä", en: "clear", kappale: 3 },
  { fi: "sumuinen", en: "foggy", kappale: 3 },
  { fi: "sataa", en: "(to) rain", kappale: 3 },
  { fi: "sateinen", en: "rainy", kappale: 3 },
  { fi: "räntä", en: "sleet", kappale: 3 },
  { fi: "lumi", en: "snow", kappale: 3 },
  { fi: "tuulla", en: "(to) blow", kappale: 3 },
  { fi: "tuulinen", en: "windy", kappale: 3 },
  { fi: "myrsky", en: "storm", kappale: 3 },
  { fi: "ukkonen", en: "thunder", kappale: 3 },
  { fi: "vuorokausi", en: "day", kappale: 3 },
  { fi: "aamu", en: "morning", kappale: 3 },
  { fi: "aamupäivä", en: "morning", kappale: 3 },
  { fi: "päivä", en: "day", kappale: 3 },
  { fi: "iltapäivä", en: "afternoon", kappale: 3 },
  { fi: "ilta", en: "evening", kappale: 3 },
  { fi: "yö", en: "night", kappale: 3 },
  { fi: "aamu(yö)", en: "early hours", kappale: 3 },
  { fi: "vuodenaika", en: "season", kappale: 3 },
  { fi: "kevät", en: "spring", kappale: 3 },
  { fi: "kesä", en: "summer", kappale: 3 },
  { fi: "syksy", en: "autumn, fall", kappale: 3 },
  { fi: "talvi", en: "winter", kappale: 3 },
  { fi: "kuukausi", en: "month", kappale: 3 },
  { fi: "tammikuu", en: "January", kappale: 3 },
  { fi: "helmikuu", en: "February", kappale: 3 },
  { fi: "maaliskuu", en: "March", kappale: 3 },
  { fi: "huhtikuu", en: "April", kappale: 3 },
  { fi: "toukokuu", en: "May", kappale: 3 },
  { fi: "kesäkuu", en: "June", kappale: 3 },
  { fi: "heinäkuu", en: "July", kappale: 3 },
  { fi: "elokuu", en: "August", kappale: 3 },
  { fi: "syyskuu", en: "September", kappale: 3 },
  { fi: "lokakuu", en: "October", kappale: 3 },
  { fi: "marraskuu", en: "November", kappale: 3 },
  { fi: "joulukuu", en: "December", kappale: 3 },
  { fi: "väri", en: "color, colour", kappale: 3 },
  { fi: "valkoinen", en: "white", kappale: 3 },
  { fi: "punainen", en: "red", kappale: 3 },
  { fi: "sininen", en: "blue", kappale: 3 },
  { fi: "keltainen", en: "yellow", kappale: 3 },
  { fi: "vihreä", en: "green", kappale: 3 },
  { fi: "musta", en: "black", kappale: 3 },
  { fi: "ruskea", en: "brown", kappale: 3 },
  { fi: "harmaa", en: "grey, gray", kappale: 3 },
  { fi: "oranssi", en: "orange", kappale: 3 },
  { fi: "lila", en: "lilac", kappale: 3 },
  { fi: "Voitko auttaa minua?", en: "Can you help me?", kappale: 3 },
  { fi: "Voitko puhua hitaasti?", en: "Can you speak slowly?", kappale: 3 },
  { fi: "Voitko sanoa uudelleen?", en: "Can you say that again?", kappale: 3 },
  { fi: "Miten sanotaan I love you suomeksi?", en: "How do you say I love you in Finnish?", kappale: 3 },
  { fi: "Mitä thank you on suomeksi?", en: "What is thank you in Finnish?", kappale: 3 },
  { fi: "Mitä sähköposti tarkoittaa?", en: "What does e-mail mean?", kappale: 3 },
  { fi: "En tiedä.", en: "I don't know.", kappale: 3 },
  { fi: "En ymmärrä.", en: "I don't understand.", kappale: 3 },
  { fi: "Kiitos avusta!", en: "Thanks for your help!", kappale: 3 },
  { fi: "Kuinka monta", en: "How many", kappale: 3 },
  { fi: "Kuinka paljon", en: "How much", kappale: 3 },
  { fi: "kieli", en: "language;tongue", kappale: 3 },
  { fi: "kerros", en: "floor;storey", kappale: 3 },
  { fi: "kauppa", en: "shop;store", kappale: 3 },
  { fi: "ilmoittautua", en: "enrol;enroll", kappale: 3 },
  { fi: "teksti", en: "text", kappale: 4 },
  { fi: "naimisissa", en: "married", kappale: 4 },
  { fi: "kanssa", en: "with", kappale: 4 },
  { fi: "rakastaa", en: "(to) love", kappale: 4 },
  { fi: "meillä on", en: "we have", kappale: 4 },
  { fi: "lapsi", en: "child", kappale: 4 },
  { fi: "söpö", en: "cute", kappale: 4 },
  { fi: "4-vuotias", en: "4 years old", kappale: 4 },
  { fi: "tyttö", en: "girl", kappale: 4 },
  { fi: "mutta", en: "but", kappale: 4 },
  { fi: "olla töissä", en: "(to) work", kappale: 4 },
  { fi: "bussikuski", en: "bus driver", kappale: 4 },
  { fi: "minulla ei ole", en: "I don't have", kappale: 4 },
  { fi: "vielä", en: "yet; still", kappale: 4 },
  { fi: "etsiä", en: "(to) look for", kappale: 4 },
  { fi: "työpaikka", en: "job", kappale: 4 },
  { fi: "sama", en: "same", kappale: 4 },
  { fi: "pitkä", en: "tall", kappale: 4 },
  { fi: "hoikka", en: "slim", kappale: 4 },
  { fi: "ujo", en: "shy", kappale: 4 },
  { fi: "vaalea", en: "blonde", kappale: 4 },
  { fi: "tukka", en: "hair", kappale: 4 },
  { fi: "sininen", en: "blue", kappale: 4 },
  { fi: "silmä", en: "eye", kappale: 4 },
  { fi: "perhe", en: "family", kappale: 4 },
  { fi: "kotona", en: "at home", kappale: 4 },
  { fi: "iso", en: "big", kappale: 4 },
  { fi: "äiti", en: "mother", kappale: 4 },
  { fi: "isä", en: "father", kappale: 4 },
  { fi: "isoveli", en: "big brother", kappale: 4 },
  { fi: "pikkusisko", en: "little sister", kappale: 4 },
  { fi: "helsinkiläinen", en: "from Helsinki", kappale: 4 },
  { fi: "talo", en: "house", kappale: 4 },
  { fi: "huone", en: "room", kappale: 4 },
  { fi: "keittiö", en: "kitchen", kappale: 4 },
  { fi: "puhelias", en: "talkative", kappale: 4 },
  { fi: "iloinen", en: "happy", kappale: 4 },
  { fi: "kihara", en: "curly", kappale: 4 },
  { fi: "tumma", en: "dark", kappale: 4 },
  { fi: "tyttöystävä", en: "girlfriend", kappale: 4 },
  { fi: "meillä ei ole", en: "we don’t have", kappale: 4 },
  { fi: "auto", en: "car", kappale: 4 },
  { fi: "ajaa", en: "(to) drive", kappale: 4 },
  { fi: "pyörä", en: "bike", kappale: 4 },
  { fi: "haluta", en: "(to) want", kappale: 4 },
  { fi: "kesäyliopisto", en: "summer university", kappale: 4 },
  { fi: "toimisto", en: "office", kappale: 4 },
  { fi: "sihteeri", en: "secretary", kappale: 4 },
  { fi: "taso", en: "level", kappale: 4 },
  { fi: "selvä", en: "clear", kappale: 4 },
  { fi: "seuraava", en: "next", kappale: 4 },
  { fi: "alkaa", en: "(to) start", kappale: 4 },
  { fi: "jo", en: "already", kappale: 4 },
  { fi: "toinen", en: "another; second", kappale: 4 },
  { fi: "parempi", en: "better", kappale: 4 },
  { fi: "vielä", en: "still; yet", kappale: 4 },
  { fi: "tila", en: "room", kappale: 4 },
  { fi: "hetkinen", en: "just a moment", kappale: 4 },
  { fi: "tarkistaa", en: "(to) check", kappale: 4 },
  { fi: "vapaa", en: "free", kappale: 4 },
  { fi: "paikka", en: "place", kappale: 4 },
  { fi: "lista", en: "list", kappale: 4 },
  { fi: "tarvita", en: "(to) need", kappale: 4 },
  { fi: "henkilötiedot", en: "personal details", kappale: 4 },
  { fi: "tässä", en: "here", kappale: 4 },
  { fi: "lomake", en: "form", kappale: 4 },
  { fi: "Millainen hän on?", en: "What’s he/she like?", kappale: 4 },
  { fi: "iloinen", en: "glad", kappale: 4 },
  { fi: "onnellinen", en: "happy", kappale: 4 },
  { fi: "surullinen", en: "sad", kappale: 4 },
  { fi: "puhelias", en: "talkative", kappale: 4 },
  { fi: "hiljainen", en: "quiet", kappale: 4 },
  { fi: "vihainen", en: "angry", kappale: 4 },
  { fi: "ystävällinen", en: "friendly", kappale: 4 },
  { fi: "kohtelias", en: "polite", kappale: 4 },
  { fi: "epäystävällinen", en: "unfriendly", kappale: 4 },
  { fi: "epäkohtelias", en: "impolite", kappale: 4 },
  { fi: "nuori", en: "young", kappale: 4 },
  { fi: "vanha", en: "old", kappale: 4 },
  { fi: "ujo", en: "shy", kappale: 4 },
  { fi: "minkänäköinen", en: "What does he/she look like?", kappale: 4 },
  { fi: "pitkä", en: "tall", kappale: 4 },
  { fi: "vaalea", en: "blonde", kappale: 4 },
  { fi: "suora", en: "straight", kappale: 4 },
  { fi: "tukka", en: "hair", kappale: 4 },
  { fi: "silmät", en: "eyes", kappale: 4 },
  { fi: "silmälasit", en: "eyeglasses", kappale: 4 },
  { fi: "kaunis", en: "beautiful", kappale: 4 },
  { fi: "nätti", en: "pretty", kappale: 4 },
  { fi: "hyvännäköinen", en: "good-looking", kappale: 4 },
  { fi: "pitkä", en: "tall", kappale: 4 },
  { fi: "hoikka", en: "slim", kappale: 4 },
  { fi: "kalju", en: "bald", kappale: 4 },
  { fi: "parta", en: "beard", kappale: 4 },
  { fi: "viikset", en: "moustache", kappale: 4 },
  { fi: "komea", en: "handsome", kappale: 4 },
  { fi: "lyhyt", en: "short", kappale: 4 },
  { fi: "tukeva", en: "sturdy", kappale: 4 },
  { fi: "lyhyt", en: "short", kappale: 4 },
  { fi: "tumma", en: "dark", kappale: 4 },
  { fi: "kihara", en: "curly", kappale: 4 },
  { fi: "söpö", en: "cute", kappale: 4 },
  { fi: "suloinen", en: "sweet", kappale: 4 },
  { fi: "perhe", en: "family", kappale: 4 },
  { fi: "isovanhemmat", en: "grandparents", kappale: 4 },
  { fi: "isoisä", en: "grandfather", kappale: 4 },
  { fi: "isoäiti", en: "grandmother", kappale: 4 },
  { fi: "vanhemmat", en: "parents", kappale: 4 },
  { fi: "isä", en: "father", kappale: 4 },
  { fi: "äiti", en: "mother", kappale: 4 },
  { fi: "mies", en: "man", kappale: 4 },
  { fi: "vaimo", en: "wife", kappale: 4 },
  { fi: "lapset", en: "children", kappale: 4 },
  { fi: "poika", en: "son", kappale: 4 },
  { fi: "tytär", en: "daughter", kappale: 4 },
  { fi: "veli", en: "brother", kappale: 4 },
  { fi: "sisko", en: "sister", kappale: 4 },
  { fi: "vauva", en: "baby", kappale: 4 },
  { fi: "naimisissa", en: "married", kappale: 4 },
  { fi: "naimaton = sinkku", en: "single", kappale: 4 },
  { fi: "kihloissa", en: "engaged", kappale: 4 },
  { fi: "eronnut", en: "divorced", kappale: 4 },
  { fi: "tyttöystävä", en: "girlfriend", kappale: 4 },
  { fi: "poikaystävä", en: "boyfriend", kappale: 4 },
  { fi: "lapsi", en: "child", kappale: 4 },
  { fi: "töissä", en: "working", kappale: 4 },
  { fi: "työtön", en: "unemployed", kappale: 4 },
  { fi: "opiskelija", en: "student", kappale: 4 },
  { fi: "eläkkeellä", en: "retired", kappale: 4 },
  { fi: "puisto", en: "park", kappale: 2 },
  { fi: "loppua", en: "(to) end", kappale: 2 },
  { fi: "kello", en: "o'clock; clock", kappale: 2 },
  { fi: "muu", en: "other", kappale: 2 },
  { fi: "opiskelija", en: "student", kappale: 2 },
  { fi: "mennä", en: "(to) go", kappale: 2 },
  { fi: "koti", en: "home", kappale: 2 },
  { fi: "mutta", en: "but", kappale: 2 },
  { fi: "kioski", en: "kiosk", kappale: 2 },
  { fi: "ostaa", en: "(to) buy", kappale: 2 },
  { fi: "jäätelö", en: "ice cream", kappale: 2 },
  { fi: "maksaa", en: "(to) cost; (to) pay", kappale: 2 },
  { fi: "euro", en: "euro", kappale: 2 },
  { fi: "säästää", en: "(to) save", kappale: 2 },
  { fi: "raha", en: "money", kappale: 2 },
  { fi: "sitten", en: "then", kappale: 2 },
  { fi: "istua", en: "(to) sit", kappale: 2 },
  { fi: "puhua", en: "(to) speak", kappale: 2 },
  { fi: "nauraa", en: "(to) laugh", kappale: 2 },
  { fi: "mistä", en: "Where are you from?", kappale: 2 },
  { fi: "brasilialainen", en: "Brazilian", kappale: 2 },
  { fi: "venäläinen", en: "Russian", kappale: 2 },
  { fi: "entä", en: "what about", kappale: 2 },
  { fi: "mistä", en: "where", kappale: 2 },
  { fi: "kotoisin", en: "from", kappale: 2 },
  { fi: "Etelä-Afrikka", en: "South Africa", kappale: 2 },
  { fi: "ai jaa", en: "okay", kappale: 2 },
  { fi: "kieli", en: "language; tongue", kappale: 2 },
  { fi: "minun", en: "my", kappale: 2 },
  { fi: "äidinkieli", en: "mother tongue", kappale: 2 },
  { fi: "englanti", en: "English", kappale: 2 },
  { fi: "myös", en: "also", kappale: 2 },
  { fi: "vähän", en: "a little", kappale: 2 },
  { fi: "espanja", en: "Spanish", kappale: 2 },
  { fi: "-kö/kö", en: "(expresses a question)", kappale: 2 },
  { fi: "sinun", en: "your", kappale: 2 },
]