import { Question } from '../types';

export const vocabulary: Question[] = [
  { fi: "Hei", en: "Hello" },
  { fi: "ja", en: "and" },
  { fi: "Tervetuloa!", en: "Welcome!" },
  { fi: "Moi!", en: "Hi!" },
  { fi: "Anteeksi!", en: "Excuse me!" },
  { fi: "onko", en: "is" },
  { fi: "täällä", en: "here" },
  { fi: "suomen kurssi", en: "course in Finnish" },
  { fi: "joo", en: "yes" },
  { fi: "Kuka sinä olet?", en: "Who are you?" },
  { fi: "minä", en: "I" },
  { fi: "olla", en: "be" },
  { fi: "entä", en: "what about" },
  { fi: "sinä", en: "you" },
  { fi: "Hauska tutustua!", en: "Nice to meet you!" },
  { fi: "Kiitos samoin!", en: "Likewise!" },
  { fi: "Mitä sinulle kuuluu?", en: "How are you?" },
  { fi: "Minulle kuuluu hyvää.", en: "I'm fine, thank you." },
  { fi: "Entä sinulle?", en: "And you?" },
  { fi: "Ihan hyvää", en: "kiitos.,I'm fine, thank you." },
  { fi: "hän", en: "he, she" },
  { fi: "Kuinka vanha sinä olet?", en: "How old are you?" },
  { fi: "opettaja", en: "teacher" },
  { fi: "tulla", en: "(to) come" },
  { fi: "Huomenta!", en: "Good morning!" },
  { fi: "Mikä sinun nimi on?", en: "What's your name?" },
  { fi: "Minun nimeni on...", en: "My name is..." },
  { fi: "Miten se kirjoitetaan?", en: "How do you spell it?" },
  { fi: "etunimi", en: "first name" },
  { fi: "sukunimi", en: "last name" },
  { fi: "Huomenta!", en: "Morning!" },
  { fi: "Hyvää huomenta!", en: "Good morning!" },
  { fi: "Päivää!", en: "Afternoon!" },
  { fi: "Hyvää päivää!", en: "Good afternoon!" },
  { fi: "Iltäa!", en: "Evening!" },
  { fi: "Hyvää iltaa!", en: "Good evening!" },
  { fi: "Hei hei!", en: "Bye bye!" },
  { fi: "Nähdään huomenna!", en: "See you tomorrow!" },
  { fi: "Moi moi!", en: "Bye!" },
  { fi: "Moikka!", en: "Bye!" },
  { fi: "Heippa!", en: "Bye!" },
  { fi: "Näkemiin!", en: "Goodbye!" },
  { fi: "Joo.", en: "Yeah." },
  { fi: "Ei.", en: "No." },
  { fi: "Kyllä.", en: "Yes." },
  { fi: "Ole hyvä!", en: "Thank you!" },
  { fi: "Kiitos!", en: "Thank you!" },
  { fi: "Ei kestä!", en: "You're welcome!" },
  { fi: "Anteeksi!", en: "Sorry!" },
  { fi: "Ei se mitään!", en: "It's all right!" },
  { fi: "Tervetuloa!", en: "Welcome!" },
  { fi: "viikonpäivät", en: "days of the week" },
  { fi: "Mikä päivä tänään on?", en: "What day is it today?" },
  { fi: "millon", en: "when" },
  { fi: "Hauskaa viikonloppua!", en: "Have a nice weekend!" },
  { fi: "maanantai", en: "Monday" },
  { fi: "tiistai", en: "Tuesday" },
  { fi: "keskiviikko", en: "Wednesday" },
  { fi: "torstai", en: "Thursday" },
  { fi: "perjantai", en: "Friday" },
  { fi: "lauantai", en: "Saturday" },
  { fi: "sunnuntai", en: "Sunday" },
  { fi: "viikonloppu", en: "weekend" },
  { fi: "toissapäivänä", en: "day before yesterday" },
  { fi: "eilen", en: "yesterday" },
  { fi: "tänään", en: "today" },
  { fi: "huomenna", en: "tomorrow" },
  { fi: "ylihuomenna", en: "day after tomorrow" },
  { fi: "nolla", en: "zero" },
  { fi: "yksi", en: "one" },
  { fi: "kaksi", en: "two" },
  { fi: "kolme", en: "three" },
  { fi: "neljä", en: "four" },
  { fi: "viisi", en: "five" },
  { fi: "kuusi", en: "six" },
  { fi: "seitsemän", en: "seven" },
  { fi: "kahdeksan", en: "eight" },
  { fi: "yhdeksän", en: "nine" },
  { fi: "kymmenen", en: "ten" },
  { fi: "yksitoista", en: "eleven" },
  { fi: "kaksitoista", en: "twelve" },
  { fi: "kolmetoista", en: "thirteen" },
  { fi: "neljätoista", en: "fourteen" },
  { fi: "viisitoista", en: "fifteen" },
  { fi: "kuusitoista", en: "sixteen" },
  { fi: "seitsemäntoista", en: "seventeen" },
  { fi: "kahdeksantoista", en: "eighteen" },
  { fi: "yhdeksäntoista", en: "nineteen" },
  { fi: "kaksikymmentä", en: "twenty" },
  { fi: "kaksikymmentäyksi", en: "twenty-one" },
  { fi: "kaksikymmentäkaksi", en: "twenty-two" },
  { fi: "kolmekymmentä", en: "thirty" },
  { fi: "neljäkymmentä", en: "forty" },
  { fi: "viisikymmentä", en: "fifty" },
  { fi: "kuusikymmentä", en: "sixty" },
  { fi: "seitsemänkymmentä", en: "seventy" },
  { fi: "kahdeksankymmentä", en: "eighty" },
  { fi: "yhdeksänkymmentä", en: "ninety" },
  { fi: "sata", en: "one hundred" },
  { fi: "satakaksi", en: "one hundred and one" },
  { fi: "kaksisataa", en: "two hundred" },
  { fi: "kolmesataa", en: "three hundred" },
  { fi: "tuhat", en: "thousand" },
  { fi: "kaksituhat", en: "two thousand" },
  { fi: "viisisataatuhatta", en: "five hundred thousand" },
  { fi: "miljoona", en: "million" },
  { fi: "kaksi miljoonaa", en: "two million" },
  { fi: "portugali", en: "Portuguese" },
  { fi: "ai niin", en: "right" },
  { fi: "tietysti", en: "of course" },
  { fi: "ajaa", en: "(to) drive" },
  { fi: "auto", en: "car" },
  { fi: "bussipysäkki", en: "bus stop" },
  { fi: "missä", en: "where" },
  { fi: "asua", en: "(to) live" },
  { fi: "numero", en: "number" },
  { fi: "vaan", en: "but" },
  { fi: "nyt", en: "now" },
  { fi: "maksaa", en: "(to) cost; (to) pay" },
  { fi: "pallo", en: "ball" },
  { fi: "ahaa", en: "oh, I see" },
  { fi: "haluaisin", en: "I would like" },
  { fi: "suklaa", en: "chocolate" },
  { fi: "okei", en: "okay" },
  { fi: "sinulle", en: "for you" },
  { fi: "myös", en: "also" },
  { fi: "vanilja", en: "vanilla" },
  { fi: "mansikka", en: "strawberry" },
  { fi: "selvä", en: "right" },
  { fi: "tuleeko muuta", en: "anything else" },
  { fi: "tässä", en: "here" },
  { fi: "euro", en: "euro" },
  { fi: "maa", en: "country; land" },
  { fi: "kansalaisuus", en: "nationality" },
  { fi: "kieli", en: "language; tongue" },
  { fi: "Suomi", en: "Finland" },
  { fi: "Ranska", en: "France" },
  { fi: "Kreikka", en: "Greece" },
  { fi: "Islanti", en: "Iceland" },
  { fi: "Egypti", en: "Egypt" },
  { fi: "Venäjä", en: "Russia" },
  { fi: "Pakistan", en: "Pakistan" },
  { fi: "suomalainen", en: "Finnish" },
  { fi: "ranskalainen", en: "French" },
  { fi: "kreikkalainen", en: "Greek" },
  { fi: "islantilainen", en: "Icelandic" },
  { fi: "egyptiläinen", en: "Egyptian" },
  { fi: "venäläinen", en: "Russian" },
  { fi: "pakistanilainen", en: "Pakistani" },
  { fi: "suomi", en: "Finnish" },
  { fi: "ranska", en: "French" },
  { fi: "kreikka", en: "Greek" },
  { fi: "islanti", en: "Icelandic" },
  { fi: "arabia", en: "Arabic" },
  { fi: "venäjä", en: "Russia" },
  { fi: "urdu", en: "Urdu" },
  { fi: "Mistä sinä olet kotoisin?", en: "Where are you from?" },
  { fi: "Minkämaalainen sinä olet?", en: "Which country are you from?" },
  { fi: "Mitä kieltä sinä puhut?", en: "What language do you speak?" },
  { fi: "Mitä sinä olet kotosin?", en: "Where do you come from?" },
  { fi: "puhua", en: "(to) speak" },
  { fi: "maailma", en: "world" },
  { fi: "pohjoinen", en: "North" },
  { fi: "Pohjois-Amerikka", en: "North America" },
  { fi: "Etelä-Amerikka", en: "South America" },
  { fi: "Eurooppa", en: "Europe" },
  { fi: "Afrikka", en: "Africa" },
  { fi: "Aasia", en: "Asia" },
  { fi: "Australia", en: "Australia" },
  { fi: "Etelämanner", en: "Antarctica" },
  { fi: "ilmansuunnat", en: "points of the compass" },
  { fi: "pohjoinen", en: "north" },
  { fi: "etelä", en: "south" },
  { fi: "itä", en: "east" },
  { fi: "länsi", en: "west" },
  { fi: "hinta", en: "price" },
  { fi: "raha", en: "money" },
  { fi: "Mitä tämä maksaa?", en: "How much does this cost?" },
  { fi: "euro", en: "euro" },
  { fi: "sentti", en: "cent" },
  { fi: "seteli", en: "note, bill" },
  { fi: "kolikko", en: "coin" },
  { fi: "halpa", en: "cheap" },
  { fi: "kallis", en: "expensive" },
  { fi: "sähköposti", en: "e-mail" },
  { fi: "mies", en: "man" },
  { fi: "hyvä", en: "good" },
  { fi: "ystävä", en: "friend" },
  { fi: "kirjoittaa", en: "(to) write" },
  { fi: "lähettäjä", en: "sender" },
  { fi: "vastaanottaja", en: "recipient" },
  { fi: "otsikko", en: "subject" },
  { fi: "terveisiiä", en: "greetings" },
  { fi: "englanniksi", en: "in English" },
  { fi: "vaan", en: "but" },
  { fi: "suomeksi", en: "in Finnish" },
  { fi: "toivottavasti", en: "hopefully" },
  { fi: "ymmärtää", en: "(to) understand" },
  { fi: "hauska", en: "funny" },
  { fi: "maanantaisin", en: "on Mondays" },
  { fi: "keskiviikkoisin", en: "on Wednesdays" },
  { fi: "torstaisin", en: "On Thursdays" },
  { fi: "meidän", en: "our" },
  { fi: "kiva", en: "nice" },
  { fi: "minun", en: "my" },
  { fi: "ystävä", en: "friend" },
  { fi: "yleensä", en: "usually" },
  { fi: "koti", en: "home" },
  { fi: "lukea", en: "(to) read" },
  { fi: "uutiset", en: "news" },
  { fi: "etsiä töitä", en: "(to) look for a job" },
  { fi: "joskus", en: "sometimes" },
  { fi: "soittaa", en: "(to) play" },
  { fi: "kitara", en: "guitar" },
  { fi: "ilta", en: "evening" },
  { fi: "olla töissä", en: "(to) work" },
  { fi: "opiskelija-asunto", en: "student apartment" },
  { fi: "pieni", en: "small" },
  { fi: "siksi", en: "that's why" },
  { fi: "muuttaa", en: "(to) move" },
  { fi: "elokuu", en: "August" },
  { fi: "uusi", en: "news" },
  { fi: "täällä", en: "here" },
  { fi: "kaunis", en: "beautiful" },
  { fi: "ilma", en: "weather; air" },
  { fi: "lämmin", en: "warm" },
  { fi: "aste", en: "degree" },
  { fi: "aurinko", en: "sun" },
  { fi: "paistaa", en: "(to) shine" },
  { fi: "yö", en: "night" },
  { fi: "joskus", en: "sometimes" },
  { fi: "vaikea", en: "hard" },
  { fi: "nukkua", en: "(to) sleep" },
  { fi: "koska", en: "because" },
  { fi: "valoisa", en: "light" },
  { fi: "millainen", en: "what kind" },
  { fi: "sää", en: "weather" },
  { fi: "paljon", en: "a lot" },
  { fi: "terveisin", en: "greetings" },
  { fi: "missä", en: "where" },
  { fi: "täällä", en: "here" },
  { fi: "tuolla", en: "over there" },
  { fi: "siellä", en: "there" },
  { fi: "nyt", en: "now" },
  { fi: "vaan", en: "but" },
  { fi: "toivottavasti", en: "hopefully" },
  { fi: "että", en: "that" },
  { fi: "myös", en: "also" },
  { fi: "yleensä", en: "usually" },
  { fi: "joskus", en: "sometimes" },
  { fi: "siksi", en: "that's why" },
  { fi: "koska", en: "because" },
  { fi: "millainen", en: "what kind" },
  { fi: "hyvä", en: "good" },
  { fi: "huono", en: "bad" },
  { fi: "kuuma", en: "hot" },
  { fi: "kylmä", en: "cold" },
  { fi: "vaikea", en: "hard" },
  { fi: "helppo", en: "easy" },
  { fi: "pieni", en: "small" },
  { fi: "iso", en: "big" },
  { fi: "suuri", en: "big" },
  { fi: "uusi", en: "new" },
  { fi: "vanha", en: "old" },
  { fi: "kaunis", en: "beautiful" },
  { fi: "ruma", en: "ugly" },
  { fi: "lämmin", en: "warm" },
  { fi: "viileä", en: "cool" },
  { fi: "valoisa", en: "light" },
  { fi: "pimeä", en: "dark" },
  { fi: "paljon", en: "a lot" },
  { fi: "vähän", en: "a little" },
  { fi: "sää", en: "weather" },
  { fi: "Millainen sää / ilma tänään on?", en: "What's the weather like today?" },
  { fi: "On kaunis / hyvä ilma.", en: "It's beautiful weather." },
  { fi: "On huono ilma.", en: "It's terrible weather." },
  { fi: "aste", en: "degree" },
  { fi: "kuuma", en: "hot" },
  { fi: "helle", en: "heat" },
  { fi: "lämmin", en: "warm" },
  { fi: "viileä", en: "cool" },
  { fi: "kylmä", en: "cold" },
  { fi: "pakkanen", en: "frost" },
  { fi: "aurinko", en: "sun" },
  { fi: "paistaa", en: "(to) shine" },
  { fi: "aurinkoinen", en: "sunny" },
  { fi: "pilvinen", en: "cloudy" },
  { fi: "puolipilvinen", en: "partly cloudy" },
  { fi: "selkeä", en: "clear" },
  { fi: "sumuinen", en: "foggy" },
  { fi: "sataa", en: "(to) rain" },
  { fi: "sateinen", en: "rainy" },
  { fi: "räntä", en: "sleet" },
  { fi: "lumi", en: "snow" },
  { fi: "tuulla", en: "(to) blow" },
  { fi: "tuulinen", en: "windy" },
  { fi: "myrsky", en: "storm" },
  { fi: "ukkonen", en: "thunder" },
  { fi: "vuorokausi", en: "day" },
  { fi: "aamu", en: "morning" },
  { fi: "aamupäivä", en: "morning" },
  { fi: "päivä", en: "day" },
  { fi: "iltapäivä", en: "afternoon" },
  { fi: "ilta", en: "evening" },
  { fi: "yö", en: "night" },
  { fi: "aamu(yö)", en: "early hours" },
  { fi: "vuodenaika", en: "season" },
  { fi: "kevät", en: "spring" },
  { fi: "kesä", en: "summer" },
  { fi: "syksy", en: "autumn, fall" },
  { fi: "talvi", en: "winter" },
  { fi: "kuukausi", en: "month" },
  { fi: "tammikuu", en: "January" },
  { fi: "helmikuu", en: "February" },
  { fi: "maaliskuu", en: "March" },
  { fi: "huhtikuu", en: "April" },
  { fi: "toukokuu", en: "May" },
  { fi: "kesäkuu", en: "June" },
  { fi: "heinäkuu", en: "July" },
  { fi: "elokuu", en: "August" },
  { fi: "syyskuu", en: "September" },
  { fi: "lokakuu", en: "October" },
  { fi: "marraskuu", en: "November" },
  { fi: "joulukuu", en: "December" },
  { fi: "väri", en: "color, colour" },
  { fi: "valkoinen", en: "white" },
  { fi: "punainen", en: "red" },
  { fi: "sininen", en: "blue" },
  { fi: "keltainen", en: "yellow" },
  { fi: "vihreä", en: "green" },
  { fi: "musta", en: "black" },
  { fi: "ruskea", en: "brown" },
  { fi: "harmaa", en: "grey, gray" },
  { fi: "oranssi", en: "orange" },
  { fi: "lila", en: "lilac" },
  { fi: "Voitko auttaa minua?", en: "Can you help me?" },
  { fi: "Voitko puhua hitaasti?", en: "Can you speak slowly?" },
  { fi: "Voitko sanoa uudelleen?", en: "Can you say that again?" },
  { fi: "Miten sanotaan I love you suomeksi?", en: "How do you say I love you in Finnish?" },
  { fi: "Mitä thank you on suomeksi?", en: "What is thank you in Finnish?" },
  { fi: "Mitä sähköposti tarkoittaa?", en: "What does e-mail mean?" },
  { fi: "En tiedä.", en: "I don't know." },
  { fi: "En ymmärrä.", en: "I don't understand." },
  { fi: "Kiitos avusta!", en: "Thanks for your help!" },
  { fi: "Kuinka monta", en: "How many" },
  { fi: "Kuinka paljon", en: "How much" }
]